version: "3.8"
services:
  tinyurl-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    networks:
      - tinyurl-net
    environment:
      environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongouser:mongopass@mongo:27017/tinydb?authSource=admin"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_SENTINEL_MASTER: "dummy-master"
      REDIS_SENTINEL_NODES: "redis:26379"
      SPRING_REDIS_SENTINEL_PASSWORD: "dummy-password"

  mongo:
    image: mongo:4.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - tinyurl-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopass

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - tinyurl-net
    environment:
      REDIS_PASSWORD: redis
    volumes:
      - redis-data:/data

networks:
  tinyurl-net:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
