apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
type: Opaque
data:
  username: bW9uZ291c2Vy         # base64 for "mongouser"
  password: bW9uZ29wYXNz         # base64 for "mongopass"
  keyfile: bXlTZWNyZXRLZXlGb3JNb25nb1JlcGxpYUNTZXQ=  # base64 for "mySecretKeyForMongoReplicaSet"
