apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyurl-app
  labels:
    app: tinyurl-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tinyurl-app
  template:
    metadata:
      labels:
        app: tinyurl-app
    spec:
      containers:
        - name: tinyurl-app
          image: gcr.io/useful-art-450916-u3/tinyurl:latest
          ports:
            - containerPort: 8080
          env:
            # MongoDB Credentials
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password

            # Redis Password (Fix: Using correct secret key name)
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: redis-password  # FIXED KEY NAME

            # Redis Sentinel Master
            - name: REDIS_SENTINEL_MASTER
              value: "mymaster"  # Matches Sentinel monitor name

            # Redis Sentinel Nodes (Updated with the correct DNS format)
            - name: REDIS_SENTINEL_NODES
              value: "my-redis.default.svc.cluster.local:26379"

            # Optional: Fallback Redis Direct Connection (if Sentinel fails)
            - name: REDIS_HOST
              value: "my-redis.default.svc.cluster.local"  # Direct Redis host
            - name: REDIS_PORT
              value: "6379"
            - name: SPRING_REDIS_LETTUCE_FORCE_LEGACY_MODE
              value: "true"
            - name: SPRING_REDIS_SENTINEL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: redis-password

