apiVersion: v1
kind: ConfigMap
metadata:
  name: tinyurl-config
data:
  REDIS_SENTINEL_MASTER: "mymaster"
  REDIS_SENTINEL_NODES: "my-redis.default.svc.cluster.local:26379"
  REDIS_HOST: "my-redis.default.svc.cluster.local"
  REDIS_PORT: "6379"
  SPRING_REDIS_LETTUCE_FORCE_LEGACY_MODE: "true"
  SPRING_REDIS_SENTINEL_PASSWORD: "redispassword"
